//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Provis.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Provis.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You already confirmed your email address!.
        /// </summary>
        internal static string AlreadyComfirmEmail {
            get {
                return ResourceManager.GetString("AlreadyComfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attachment not found.
        /// </summary>
        internal static string AttachmentNotFound {
            get {
                return ResourceManager.GetString("AttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad sprint value.
        /// </summary>
        internal static string BadSprintValue {
            get {
                return ResourceManager.GetString("BadSprintValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot accept this invite.
        ///   Ищет локализованную строку, похожую на You cannot accept this invite.
        /// </summary>
        internal static string CannotAcceptInvite {
            get {
                return ResourceManager.GetString("CannotAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot deny this invite.
        /// </summary>
        internal static string CannotDenyInvite {
            get {
                return ResourceManager.GetString("CannotDenyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not get content type of file.
        /// </summary>
        internal static string CannotGetFileContentType {
            get {
                return ResourceManager.GetString("CannotGetFileContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot save the file.
        /// </summary>
        internal static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment not found.
        /// </summary>
        internal static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data has been modified by another user.
        /// </summary>
        internal static string ConcurrencyCheck {
            get {
                return ResourceManager.GetString("ConcurrencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong code or this code is deprecated, try again!.
        /// </summary>
        internal static string ConfirmEmailInvalidCode {
            get {
                return ResourceManager.GetString("ConfirmEmailInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First you need to confirm your email address.
        /// </summary>
        internal static string EmailNotConfirm {
            get {
                return ResourceManager.GetString("EmailNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This file is empty.
        /// </summary>
        internal static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File with this name already exist.
        /// </summary>
        internal static string FileNameAlreadyExist {
            get {
                return ResourceManager.GetString("FileNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image not found.
        /// </summary>
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password.
        /// </summary>
        internal static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalide Code.
        /// </summary>
        internal static string Invalid2FVCode {
            get {
                return ResourceManager.GetString("Invalid2FVCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid 2-step verification provider.
        /// </summary>
        internal static string Invalid2StepVerification {
            get {
                return ResourceManager.GetString("Invalid2StepVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Due date should be not in the past.
        /// </summary>
        internal static string InvalidDateOfEnd {
            get {
                return ResourceManager.GetString("InvalidDateOfEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File must be image.
        /// </summary>
        internal static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid request.
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Story points most be greater than 0 and less 100.
        /// </summary>
        internal static string InvalidStoryPoints {
            get {
                return ResourceManager.GetString("InvalidStoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid refrash token.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid token verification.
        /// </summary>
        internal static string InvalidTokenVerification {
            get {
                return ResourceManager.GetString("InvalidTokenVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have already confirmed this invitation.
        /// </summary>
        internal static string InviteAlreadyAccerted {
            get {
                return ResourceManager.GetString("InviteAlreadyAccerted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This invite not found or it already answered.
        /// </summary>
        internal static string InviteNotFound {
            get {
                return ResourceManager.GetString("InviteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You don`t have permissions.
        /// </summary>
        internal static string NotPermission {
            get {
                return ResourceManager.GetString("NotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only creator of the task can assign another users.
        /// </summary>
        internal static string NotPermissionAssignUser {
            get {
                return ResourceManager.GetString("NotPermissionAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only cretor or workspace owner can delete comments.
        /// </summary>
        internal static string NotPermissionDeleteComment {
            get {
                return ResourceManager.GetString("NotPermissionDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only creator can edit his comment.
        /// </summary>
        internal static string NotPermissionEditComment {
            get {
                return ResourceManager.GetString("NotPermissionEditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No preview for this file.
        /// </summary>
        internal static string NotPreview {
            get {
                return ResourceManager.GetString("NotPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Owner can&apos;t leave workspace.
        /// </summary>
        internal static string OwnerCannotLeaveWorkspace {
            get {
                return ResourceManager.GetString("OwnerCannotLeaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You cannot send invite to your account.
        /// </summary>
        internal static string SendInviteYourself {
            get {
                return ResourceManager.GetString("SendInviteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint not found.
        /// </summary>
        internal static string SprintNotFound {
            get {
                return ResourceManager.GetString("SprintNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprints already off.
        /// </summary>
        internal static string SprintsAlreadyOff {
            get {
                return ResourceManager.GetString("SprintsAlreadyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprints already on.
        /// </summary>
        internal static string SprintsAlreadyOn {
            get {
                return ResourceManager.GetString("SprintsAlreadyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t add sprint, because it isn&apos;t used in this workspace.
        /// </summary>
        internal static string SprintsNotOn {
            get {
                return ResourceManager.GetString("SprintsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found.
        ///   Ищет локализованную строку, похожую на Task not found.
        /// </summary>
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This status not exist.
        /// </summary>
        internal static string TaskStatusNotFound {
            get {
                return ResourceManager.GetString("TaskStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transaction failed.
        /// </summary>
        internal static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown error has occured.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This user already accepted your invite.
        /// </summary>
        internal static string UserAcceptedInvite {
            get {
                return ResourceManager.GetString("UserAcceptedInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This user has already assigned.
        /// </summary>
        internal static string UserAlreadyAssigned {
            get {
                return ResourceManager.GetString("UserAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User already has invite, wait for a answer.
        /// </summary>
        internal static string UserAlreadyHasInvite {
            get {
                return ResourceManager.GetString("UserAlreadyHasInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User with this usernamre already exist.
        /// </summary>
        internal static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This user doesn&apos;t member of current workspace.
        /// </summary>
        internal static string UserNotMember {
            get {
                return ResourceManager.GetString("UserNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workspace ot found.
        /// </summary>
        internal static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
    }
}
